### ISSUE TITLE
Minification

### ISSUE THREAD

**Issue by ChrisAntaki** [vgturtle127/8bitimager#1]
Cool project! If you're up for it, providing an unminified version of the script would help people examine the logic behind it.

**Comment by vgturtle127** [comment]
@ChrisAntaki I'm sorry, I never saw this issue when it was posted. You are right, I will have to look into that.

**Comment by ChrisAntaki** [comment]
Sweet!

**Comment by vgturtle127** [comment]
@ChrisAntaki I un-minified the source, so you can browse to your hearts content. :smile: 

I also added some info to the file, and I want to comment the source as much as possible in the future.
